// Textos de la interfaz (RNF.5)
export const textos = {
  es: {
    menu_habitaciones: 'Habitaciones',
    menu_mis_reservas: 'Mis reservas',
    marca_reservas: 'Reservas',
    cambiar_idioma: 'Cambiar idioma a inglés',
    salir: 'Salir',
    ingresar: 'Ingresar',
    pie: 'Reservas en línea',
    cargando: 'Cargando...',
    procesando: 'Procesando...',

    estado_confirmada: 'Confirmada',
    estado_pendiente: 'Pendiente de pago',
    estado_cancelada: 'Cancelada',
    estado_aprobado: 'Aprobado',
    estado_rechazado: 'Rechazado',

    catalogo_kicker: 'Estadía frente al mar',
    catalogo_titulo: 'Encuentra tu habitación',
    catalogo_bajada: 'Elige tus fechas y revisa las habitaciones disponibles del Hotel Pacific Reef.',
    llegada: 'Llegada',
    salida: 'Salida',
    buscar: 'Buscar',
    buscando: 'Buscando...',
    resultado_catalogo: '{cantidad} habitaciones en el catálogo',
    resultado_busqueda: '{cantidad} habitaciones disponibles · {noches} noches',
    ver_todas: 'Ver todo el catálogo',
    sin_disponibles: 'No hay habitaciones disponibles en esas fechas. Prueba con otro rango.',
    foto_habitacion: 'Fotografía de la habitación {numero}',
    foto_detalle: 'Fotografía {indice} de la habitación {numero}',
    turista: 'Turista',
    habitacion: 'Habitación',
    huespedes: '{cantidad} huéspedes',
    clp_por_noche: 'CLP por noche',
    ver_disponibilidad: 'Ver disponibilidad',
    nota_dolar: 'Valores en dólares aproximados con el dólar observado de $ {valor} del {fecha} (fuente: mindicador.cl).',

    paso: 'Paso {actual} de {total}',
    precio_diario: 'Precio diario',
    mes_anterior: 'Mes anterior',
    mes_siguiente: 'Mes siguiente',
    ocupado: 'ocupado',
    leyenda_elegida: 'Tu estadía',
    leyenda_ocupada: 'Ocupado',
    elige_llegada: 'Toca un día para elegir la llegada',
    elige_salida: 'Ahora toca el día de salida',
    disponible_noches: 'Disponible para {noches} noches.',
    no_disponible: 'La habitación no está disponible en todo ese rango.',
    sugerencia_reducir: 'Puedes reducir la estadía a {noches} noches, con salida el {fecha}.',
    aplicar: 'Aplicar',
    sugerencia_otras: 'O elegir otra habitación libre en esas mismas fechas:',
    valor_total: 'Valor total',
    abono_ahora: '30% a pagar ahora',
    confirmar_reserva: 'Confirmar reserva',
    solo_clientes: 'Solo las cuentas de cliente pueden reservar.',
    requiere_ingreso: 'Te pediremos iniciar sesión para registrar la reserva a tu nombre.',

    pago_titulo: 'Completa el pago',
    pago_listo_titulo: 'Reserva confirmada',
    pago_bajada: 'Pagas el 30% ahora y el saldo al llegar al hotel.',
    reserva_confirmada: 'Tu habitación quedó reservada',
    ir_mis_reservas: 'Ir a mis reservas',
    metodo_pago: 'Método de pago',
    tipo_tarjeta: 'Tipo de tarjeta',
    tarjeta_credito: 'Tarjeta de crédito',
    tarjeta_debito: 'Tarjeta de débito',
    titular: 'Titular de la tarjeta',
    numero_tarjeta: 'Número de tarjeta',
    vencimiento: 'Vencimiento',
    correo_ticket: 'El ticket con código QR se enviará a {correo}.',
    pagar: 'Pagar {monto} CLP',
    ambiente_prueba_pago: 'Ambiente de prueba: la tarjeta 4242 4242 4242 4242 se aprueba y la 4000 0000 0000 0002 se rechaza.',
    resumen_reserva: 'Resumen de reserva',
    noches: '{cantidad} noches',
    saldo_llegada: 'Saldo a pagar al llegar',
    pago_hoy: 'Pago de hoy: {monto} CLP',
    estado_operacion: 'Estado de la operación',
    estado_procesando: 'Procesando',
    estado_procesando_detalle: 'Verificando con tu banco',
    estado_aprobado_detalle: 'Pago confirmado',
    estado_rechazado_detalle: 'Reintenta o usa otra tarjeta',

    ticket_titulo: 'Ticket de reserva',
    ticket_qr_alt: 'Código QR del ticket {codigo}',
    ticket_qr_pendiente: 'QR en proceso',
    ticket_enviado: 'Ticket enviado a {correo}.',
    ticket_simulado: 'Ticket emitido para {correo}. En el ambiente de prueba el envío por correo es simulado.',
    ticket_instruccion: 'Presenta este código QR en el check-in.',

    mis_reservas_kicker: 'Tu cuenta',
    mis_reservas_bajada: 'Revisa tus reservas, paga el abono pendiente o descarga tu ticket.',
    sin_reservas: 'Aún no tienes reservas.',
    pagado: 'Pagado',
    saldo: 'Saldo',
    pagar_abono: 'Pagar 30%',
    cancelar: 'Cancelar',
    ver_ticket: 'Ver ticket',
    ocultar_ticket: 'Ocultar ticket',

    acceso_kicker: 'Hotel Pacific Reef',
    ingreso_titulo: 'Inicia sesión',
    ingreso_bajada: 'Accede con tu correo y contraseña.',
    correo: 'Correo electrónico',
    contrasena: 'Contraseña',
    sin_cuenta: '¿No tienes cuenta?',
    crear_cuenta: 'Crear cuenta',
    con_cuenta: '¿Ya tienes cuenta?',
    registro_titulo: 'Crea tu cuenta',
    registro_bajada: 'Regístrate para reservar y pagar en línea.',
    nombre_completo: 'Nombre completo',
    telefono: 'Teléfono',
    repetir_contrasena: 'Repite la contraseña',
    regla_contrasena: 'Mínimo 8 caracteres, con letras y números.',
    contrasenas_distintas: 'Las contraseñas no coinciden.'
  },
  en: {
    menu_habitaciones: 'Rooms',
    menu_mis_reservas: 'My bookings',
    marca_reservas: 'Bookings',
    cambiar_idioma: 'Switch language to Spanish',
    salir: 'Sign out',
    ingresar: 'Sign in',
    pie: 'Online bookings',
    cargando: 'Loading...',
    procesando: 'Processing...',

    estado_confirmada: 'Confirmed',
    estado_pendiente: 'Payment pending',
    estado_cancelada: 'Cancelled',
    estado_aprobado: 'Approved',
    estado_rechazado: 'Declined',

    catalogo_kicker: 'Oceanfront stay',
    catalogo_titulo: 'Find your room',
    catalogo_bajada: 'Choose your dates and browse the available rooms at Hotel Pacific Reef.',
    llegada: 'Check-in',
    salida: 'Check-out',
    buscar: 'Search',
    buscando: 'Searching...',
    resultado_catalogo: '{cantidad} rooms in the catalog',
    resultado_busqueda: '{cantidad} rooms available · {noches} nights',
    ver_todas: 'See full catalog',
    sin_disponibles: 'No rooms are available on those dates. Try another range.',
    foto_habitacion: 'Photo of room {numero}',
    foto_detalle: 'Photo {indice} of room {numero}',
    turista: 'Tourist',
    habitacion: 'Room',
    huespedes: '{cantidad} guests',
    clp_por_noche: 'CLP per night',
    ver_disponibilidad: 'Check availability',
    nota_dolar: 'Dollar amounts are approximate, using the observed exchange rate of CLP {valor} on {fecha} (source: mindicador.cl).',

    paso: 'Step {actual} of {total}',
    precio_diario: 'Nightly rate',
    mes_anterior: 'Previous month',
    mes_siguiente: 'Next month',
    ocupado: 'booked',
    leyenda_elegida: 'Your stay',
    leyenda_ocupada: 'Booked',
    elige_llegada: 'Tap a day to choose check-in',
    elige_salida: 'Now tap the check-out day',
    disponible_noches: 'Available for {noches} nights.',
    no_disponible: 'The room is not available for that whole range.',
    sugerencia_reducir: 'You can shorten your stay to {noches} nights, checking out on {fecha}.',
    aplicar: 'Apply',
    sugerencia_otras: 'Or choose another room that is free on the same dates:',
    valor_total: 'Total',
    abono_ahora: '30% to pay now',
    confirmar_reserva: 'Confirm booking',
    solo_clientes: 'Only customer accounts can make bookings.',
    requiere_ingreso: 'We will ask you to sign in to register the booking in your name.',

    pago_titulo: 'Complete your payment',
    pago_listo_titulo: 'Booking confirmed',
    pago_bajada: 'You pay 30% now and the balance on arrival.',
    reserva_confirmada: 'Your room is booked',
    ir_mis_reservas: 'Go to my bookings',
    metodo_pago: 'Payment method',
    tipo_tarjeta: 'Card type',
    tarjeta_credito: 'Credit card',
    tarjeta_debito: 'Debit card',
    titular: 'Cardholder name',
    numero_tarjeta: 'Card number',
    vencimiento: 'Expiry date',
    correo_ticket: 'The ticket with the QR code will be sent to {correo}.',
    pagar: 'Pay {monto} CLP',
    ambiente_prueba_pago: 'Test environment: card 4242 4242 4242 4242 is approved and 4000 0000 0000 0002 is declined.',
    resumen_reserva: 'Booking summary',
    noches: '{cantidad} nights',
    saldo_llegada: 'Balance due on arrival',
    pago_hoy: 'Payment today: {monto} CLP',
    estado_operacion: 'Payment status',
    estado_procesando: 'Processing',
    estado_procesando_detalle: 'Checking with your bank',
    estado_aprobado_detalle: 'Payment confirmed',
    estado_rechazado_detalle: 'Try again or use another card',

    ticket_titulo: 'Booking ticket',
    ticket_qr_alt: 'QR code for ticket {codigo}',
    ticket_qr_pendiente: 'QR in progress',
    ticket_enviado: 'Ticket sent to {correo}.',
    ticket_simulado: 'Ticket issued for {correo}. In the test environment the email is simulated.',
    ticket_instruccion: 'Show this QR code at check-in.',

    mis_reservas_kicker: 'Your account',
    mis_reservas_bajada: 'Review your bookings, pay a pending deposit or view your ticket.',
    sin_reservas: 'You have no bookings yet.',
    pagado: 'Paid',
    saldo: 'Balance',
    pagar_abono: 'Pay 30%',
    cancelar: 'Cancel',
    ver_ticket: 'View ticket',
    ocultar_ticket: 'Hide ticket',

    acceso_kicker: 'Hotel Pacific Reef',
    ingreso_titulo: 'Sign in',
    ingreso_bajada: 'Use your email and password.',
    correo: 'Email',
    contrasena: 'Password',
    sin_cuenta: "Don't have an account?",
    crear_cuenta: 'Create account',
    con_cuenta: 'Already have an account?',
    registro_titulo: 'Create your account',
    registro_bajada: 'Sign up to book and pay online.',
    nombre_completo: 'Full name',
    telefono: 'Phone',
    repetir_contrasena: 'Repeat password',
    regla_contrasena: 'At least 8 characters, with letters and numbers.',
    contrasenas_distintas: 'The passwords do not match.'
  }
};
